<?php

$productType = $block->getProductType();
$productPriceConfig = $block->getProductConfPrice();
$productPrice = $block->getProductPrice();

if ($productType == 'configurable') {
    $price = $productPriceConfig / 4;
} else {
    $price = $productPrice / 4;
}
?>

<p class="or"><?= __('or') ?></p>
<h2 class="intrest_price">
    <p class="inst"><?= _('4 ') ?><strong><?= _('Intrest Free ') ?></strong><?= _('Payments of ') ?></p><?= $this->helper('Magento\Framework\Pricing\Helper\Data')->currency(number_format($price, 2), true, false); ?>
</h2>